Hibernate work #1
grom4er/cinema pull request #1
Opened 2021-01-26 15:49 UTC by grom4er

2021-01-26 16:04 UTC, Max-Pochepets approved these changes
make sure all your files have empty lines in the end

2021-01-26 16:04 UTC, Max-Pochepets commented on src/main/java/cinema/Application.java
> +
```suggestion
```

2021-01-26 16:08 UTC, grom4er commented on src/main/java/cinema/Application.java
> +
Это я с тревисом игрался!

2021-01-26 16:33 UTC, Sofasmile requested changes

2021-01-26 16:33 UTC, Sofasmile commented on .travis.yml
> +    - $HOME/.m2
let's add empty line at the end of the file

2021-01-26 16:33 UTC, Sofasmile commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert movie entity", e);
```suggestion
            throw new DataProcessingException("Can't insert movie entity " + movie, e);
```

2021-01-26 16:33 UTC, Sofasmile commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
empty line

2021-01-26 16:33 UTC, Sofasmile commented on travis.yml
> +language: java
do we need two travis.yml file?

2021-01-27 07:13 UTC, Sofasmile commented
firstly you should fix the conflict

2021-01-27 07:46 UTC, Sofasmile approved these changes

2021-01-27 08:29 UTC, merged