HB-04
grom4er/cinema pull request #2
Opened 2021-02-01 14:01 UTC by grom4er

2021-02-01 14:32 UTC, Max-Pochepets requested changes

2021-02-01 14:32 UTC, Max-Pochepets commented on src/main/java/cinema/Application.java
> +        movieSession.setShowTime(LocalDateTime.now());
Я бы четче указал парамеры `LocalDateTime`, а вдруг будет компьютер который обработает следущее вхождение `.now` через секунду. Немного не логично как по мне.

2021-02-01 14:32 UTC, Max-Pochepets commented on src/main/java/cinema/dao/CinemaHallDaoImpl.java
> +            throw new DataProcessingException("Can't insert movie entity", e);
[don't](https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_04.html) just copy paste your Dao methods.

2021-02-01 14:32 UTC, Max-Pochepets commented on src/main/java/cinema/dao/MovieSessionDaoImpl.java
> +                    + "where ms.movie.id =:movie_id "
Ну, ты уже в курсе :) если ты не переопределяешь `FetchType` на Лесю - эти join здесь не нужны.

2021-02-01 15:22 UTC, Max-Pochepets approved these changes
👍

2021-02-01 15:22 UTC, Max-Pochepets commented on src/main/java/cinema/dao/CinemaHallDaoImpl.java
> +            throw new DataProcessingException("Can't insert cinema hall entity", e);
```suggestion
            throw new DataProcessingException("Can't get a list of cinema hall entities", e);
```

2021-02-01 18:03 UTC, KseniiaMakarova requested changes

2021-02-02 05:43 UTC, grom4er commented on src/main/java/cinema/Application.java
> +        movieSession.setShowTime(LocalDateTime.of(2021,02,1,15,5));
Надеюсь исправилось, потому что из-за подсказок ide я не вижу.

2021-02-02 06:11 UTC, KseniiaMakarova requested changes
let's fix travis - too long line

2021-02-02 09:51 UTC, KseniiaMakarova approved these changes

2021-02-02 09:52 UTC, merged