HM_hibernate06
grom4er/cinema pull request #4
Opened 2021-02-03 18:32 UTC by grom4er

2021-02-03 19:11 UTC, Max-Pochepets requested changes

2021-02-03 19:11 UTC, Max-Pochepets commented on src/main/java/cinema/Application.java
> +        // authenticationService.login(user.getEmail(),"1222");
delete this please

2021-02-03 19:11 UTC, Max-Pochepets commented on src/main/java/cinema/model/ShoppingCart.java
> +@Table(name = "shoppingCart")
```suggestion
@Table(name = "shopping_carts")
```
same for others

2021-02-03 19:11 UTC, Max-Pochepets commented on src/main/java/cinema/service/ShoppingCartService.java
> +     */
#remove

2021-02-03 19:11 UTC, Max-Pochepets commented on src/main/java/cinema/service/impl/ShoppingCartServiceImpl.java
> +
```suggestion
```

2021-02-03 19:18 UTC, Max-Pochepets approved these changes
👍

2021-02-04 07:25 UTC, KseniiaMakarova requested changes

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/Application.java
> +        user.setPassword("123");
let's save this user to the db

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/model/MovieSession.java
> -    @JoinColumn(name = "movie_id")
there is no need to remove `@JoinColumn` annotations)

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/model/ShoppingCart.java
> +@Table(name = "shopping_carts")
let's use either singular or plural table names for all the tables

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/model/ShoppingCart.java
> +    @OneToMany(cascade = CascadeType.ALL)
let's remove this - we should be very careful with cascades - especially with those that include DELETE operation

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/model/Ticket.java
> +    @JoinColumn(name = "movieId")
```suggestion
    @JoinColumn(name = "movie_id")
```
remember about the correct column naming

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/service/impl/ShoppingCartServiceImpl.java
> +    private TicketDao ticketDao;
let's use this to save the created ticket to the DB - but do this after you already get the shoppingCart from the DB

2021-02-04 07:25 UTC, KseniiaMakarova commented on src/main/java/cinema/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCartByUser = getByUser(shoppingCart.getUser());
do you need this?

2021-02-04 09:30 UTC, KseniiaMakarova approved these changes

2021-02-04 10:02 UTC, merged