Spring
grom4er/cinema pull request #6
Opened 2021-02-11 13:25 UTC by grom4er

Add spring to project

2021-02-11 13:26 UTC, Resci approved these changes

2021-02-11 14:17 UTC, Sofasmile requested changes

2021-02-11 14:17 UTC, Sofasmile commented on src/main/java/cinema/dao/impl/CinemaHallDaoImpl.java
> +    @Autowired
which type of Autowired do you use? via field or via constructor?

2021-02-11 14:40 UTC, grom4er commented on src/main/java/cinema/dao/impl/CinemaHallDaoImpl.java
> +    @Autowired
В моем случае используется конструктор, и видимо я забыл удалить аннотацию (но как)

2021-02-11 16:12 UTC, Sofasmile approved these changes

2021-02-12 07:33 UTC, Sofasmile commented on src/main/java/cinema/config/AppConfig.java
> +@ComponentScan(basePackages = {
we should add `security` too

2021-02-15 02:26 UTC, merged