dev_petrovSpring
grom4er/cinema pull request #8
Opened 2021-02-16 15:22 UTC by grom4er

add OrderController, AuthenticationController, UserController, ShoppingCartController
add to them DTO and map DTO

2021-02-16 15:47 UTC, Max-Pochepets requested changes

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/controller/AuthenticationController.java
> +@RequestMapping
I don't think we need this annotation

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/controller/AuthenticationController.java
> +    public void register(@RequestBody UserRequestDto dto) throws RegistrationException {
```suggestion
    public void register(@RequestBody UserRequestDto dto) {
```
I didn't see you throw this anywhere

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/controller/OrderController.java
> +    @GetMapping()
```suggestion
    @GetMapping
```

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto add(@RequestParam Long userId,
personally I would not return anything in POST requests

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/dto/mapper/impl/UserMapper.java
> +
```suggestion
```

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/dto/response/OrderResponseDto.java
> +    private List<Long> ticketsId;
```suggestion
    private List<Long> ticketIds;
```

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/dto/response/ShoppingCartResponseDto.java
> +    private List<Long> ticketsId;
same

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/exception/DataProcessingException.java
> +    }
Why?

2021-02-16 15:47 UTC, Max-Pochepets commented on src/main/java/cinema/service/impl/MovieSessionServiceImpl.java
> +    public Optional<MovieSession> getById(Long id) {
I think it's better to return an Entity from service layer, applying all the operations we need with Optional in it

2021-02-16 15:53 UTC, grom4er commented on src/main/java/cinema/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto add(@RequestParam Long userId,
В первую очередь, это чтоб видеть результат для тестов)

2021-02-16 16:02 UTC, grom4er commented on src/main/java/cinema/service/impl/MovieSessionServiceImpl.java
> +    public Optional<MovieSession> getById(Long id) {
на данный момент мы считаем что данные нам прийдут валидные

2021-02-16 16:32 UTC, Max-Pochepets approved these changes

2021-02-16 17:24 UTC, KseniiaMakarova requested changes

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/AuthenticationController.java
> +    private final UserMapper userMapper;
do we use this?

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/ShoppingCartController.java
> +                .collect(Collectors.toList()));
for this method - let's better remove this and return void
or use your mapper

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/UserController.java
> +    public UserResponseDto get(@RequestParam String email) {
```suggestion
    public UserResponseDto getByEmail(@RequestParam String email) {
```

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto get(@RequestParam Long userId) {
make the method name informative

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto add(@RequestParam Long userId,
same
```suggestion
    public ShoppingCartResponseDto addSession(@RequestParam Long userId,
```

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/OrderController.java
> +    public List<OrderResponseDto> get(@RequestParam Long userId) {
same

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/mapper/RequestDtoMapper.java
> +    I mapToObject(T entity);
```suggestion
    I mapToObject(T requestDto);
```

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/mapper/impl/OrderMapper.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
is it a constant?

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/mapper/impl/OrderMapper.java
> +    private final OrderService orderService;
do we use this?

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/mapper/impl/UserMapper.java
> +    private final UserService userService;
do we need this?

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/mapper/impl/UserMapper.java
> +    public User mapToObject(UserRequestDto entity) {
do we use this method?

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/request/UserRequestDto.java
> +    private String pwd;
```suggestion
    private String password;
```

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/service/MovieSessionService.java
> +    Optional<MovieSession> getById(Long id);
```suggestion
    MovieSession getById(Long id);
```
return Optional from the dao layer, and entity from the service layer

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/service/UserService.java
> +    Optional<User> getById(Long id);
same here

2021-02-16 17:24 UTC, KseniiaMakarova commented on src/main/java/cinema/service/UserService.java
>      Optional<User> findByEmail(String email);
but not here - for this method we should still return Optional from service layer as well

2021-02-16 17:50 UTC, grom4er commented on src/main/java/cinema/dto/mapper/impl/UserMapper.java
> +    public User mapToObject(UserRequestDto entity) {
в 4 местах.

2021-02-17 10:50 UTC, KseniiaMakarova approved these changes

2021-02-17 10:50 UTC, KseniiaMakarova commented on src/main/java/cinema/dto/mapper/impl/UserMapper.java
> +    public User mapToObject(UserRequestDto requestDto) {
where do you use mapper to make User from UserRequestDto?

2021-02-17 14:44 UTC, grom4er commented on src/main/java/cinema/dto/mapper/impl/UserMapper.java
> +    public User mapToObject(UserRequestDto requestDto) {
Когда нам приходит DTO для добавления в базу. 
Добавлять его мы не будем, только объект. Хотя, в моем случае сейчас поля и совпадают - но это может измениться в любой момент.

2021-02-17 14:45 UTC, merged