dev_petrovSpring
grom4er/cinema pull request #9
Opened 2021-02-18 08:50 UTC by grom4er

2021-02-18 10:28 UTC, Max-Pochepets approved these changes

2021-02-18 10:28 UTC, Max-Pochepets commented on src/main/java/cinema/config/CustomGlobalExceptionHandler.java
> +        //Get all errors
```suggestion
```
don't push comments)

2021-02-18 10:28 UTC, Max-Pochepets commented on src/main/java/cinema/config/SecureConfig.java
> +                .permitAll()
```suggestion
                .formLogin().permitAll()
```
leave permissions on the same page with endpoints

2021-02-18 12:51 UTC, boroda4436 requested changes

2021-02-18 12:51 UTC, boroda4436 commented on src/main/java/cinema/util/validate/impl/ValidatePasswords.java
> +        } else {
do not complicate if-else statements

2021-02-19 07:38 UTC, boroda4436 approved these changes

2021-02-19 07:47 UTC, merged